version: '2'
services:

  db:
    image: mariadb:10.1
    container_name: nb_mariadb
    restart: always
    volumes:
      - ./docker/mysql/initdb/:/docker-entrypoint-initdb.d
      - "mysqldata:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=123132123
      - MYSQL_DATABASE=nb_db
      - MYSQL_USER=newborn
      - MYSQL_PASSWORD=123456
    ports:
      - 3306:3306
    networks:
      - backend

  php:
    build: ./docker/php
    container_name: nb_php-fpm
    restart: always
    volumes:
      - .:/var/www/html
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/logs/php-fpm:/var/log/php-fpm
    expose:
      - "9000"
    networks:
      - backend

  nginx:
    image: nginx:stable-alpine
    container_name: nb_nginx
    restart: always
    volumes:
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/logs/nginx:/var/log/nginx
    volumes_from:
      - php
    ports:
      - 8080:80
    networks:
      - backend
      - frontend

  memcached:
    image: memcached:1.4.31-alpine
    container_name: nb_memcached
    expose:
      - "11211"
    networks:
      - backend   

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: nb_phpmyadmin
    restart: always
    ports:
      - "8000:80"
    networks:
      - backend
      - frontend

volumes:
    mysqldata:
        driver: local

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
