version: '2'
services:

  db:
    image: mariadb:10.1
    container_name: nb_api_mariadb
    restart: always
    volumes:
      - ./docker/mysql/initdb/:/docker-entrypoint-initdb.d
      - apidata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123132123
      - MYSQL_DATABASE=nb_db
      - MYSQL_USER=newborn
      - MYSQL_PASSWORD=123456
    expose:
      - "3306"
    networks:
      - nb_api_backend

  php:
    build: ./docker/php
    container_name: nb_api_php-fpm
    restart: always
    volumes:
      - .:/var/www/html
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/logs/php-fpm:/var/log/php-fpm
    expose:
      - "9000"
    networks:
      - nb_api_backend

  nginx:
    image: nginx:stable-alpine
    container_name: nb_api_nginx
    restart: always
    volumes:
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/logs/nginx:/var/log/nginx
    volumes_from:
      - php
    ports:
      - 7070:80
    networks:
      - nb_api_backend

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: nb_api_phpmyadmin
    restart: always
    ports:
      - "7000:80"
    networks:
      - nb_api_backend

volumes:
    apidata:
        driver: local

networks:
    nb_api_backend:
        driver: bridge
